In [1]:
import numpy as np
from numpy.linalg import eig, inv, det
from PIL import Image

In [9]:
#Q1
#(a)Reverse NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
print( arr[::-1])

[5 4 6 3 2 1]


In [11]:
# (b) Flatten array
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("ravel:", array1.ravel())
print("flatten():", array1.flatten())

ravel: [1 2 3 2 4 5 1 2 3]
flatten(): [1 2 3 2 4 5 1 2 3]


In [13]:
# (c) Compare arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Array equal:", np.array_equal(arr1, arr2))

Array equal: True


In [15]:
# (d) Most frequent values and indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
vals_x, counts_x = np.unique(x, return_counts=True)
vals_y, counts_y = np.unique(y, return_counts=True)
most_freq_x = vals_x[np.argmax(counts_x)]
most_freq_y = vals_y[np.argmax(counts_y)]
print("x most freq value:", most_freq_x, "indices:", np.where(x==most_freq_x)[0])
print("y most freq value:", most_freq_y, "indices:", np.where(y==most_freq_y)[0])

x most freq value: 1 indices: [0 5 7 8 9]
y most freq value: 1 indices: [0 1 2]


In [23]:
# (e) Matrix sums
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("1) Total sum:", gfg.sum())
print("2) Row-wise sum:", gfg.sum(axis=1))
print("3) Column-wise sum:", gfg.sum(axis=0))

1) Total sum: 45
2) Row-wise sum: [[14]
 [16]
 [15]]
3) Column-wise sum: [[20  9 16]]


In [25]:
# (f) Matrix operations
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("(i) Diagonal sum:", np.trace(n_array))
eigenvalues, eigenvectors = eig(n_array)
print("(ii) Eigen values:", eigenvalues)
print("(iii) Eigen vectors:\n", eigenvectors)
print("(iv) Inverse:\n", inv(n_array))
print("(v) Determinant:", det(n_array))

(i) Diagonal sum: 176
(ii) Eigen values: [98.16835147 28.097044   49.73460452]
(iii) Eigen vectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
(iv) Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
(v) Determinant: 137180.0000000001


In [31]:
# (h) Inner, Outer, Cartesian product
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner:\n", np.inner(x, y))
print("Outer:\n", np.outer(x, y))
print("Cartesian:\n", np.tensordot(x, y, axes=0))

Inner:
 [[17 52]
 [13 62]]
Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian:
 [[[[ 2 10  0]
   [10 20  6]]

  [[ 3 15  0]
   [15 30  9]]

  [[ 4 20  0]
   [20 40 12]]]


 [[[ 3 15  0]
   [15 30  9]]

  [[ 2 10  0]
   [10 20  6]]

  [[ 9 45  0]
   [45 90 27]]]]


In [37]:
# Q2
array = np.array([[1, -2, 3],[-4, 5, -6]])
# (a)(i)
print("Q2(a)(i) Abs:\n", np.abs(array))


# (a)(ii)
flat = array.flatten()
print("Q2(a)(ii) Percentiles (flat):", np.percentile(flat, [25,50,75]))
print("Per column:", np.percentile(array, [25,50,75], axis=0))
print("Per row:", np.percentile(array, [25,50,75], axis=1))


# (a)(iii)
print("Q2(a)(iii) Mean(flat):", np.mean(flat), "Median(flat):", np.median(flat), "Std(flat):", np.std(flat))
print("Per column mean:", np.mean(array,axis=0), "median:", np.median(array,axis=0), "std:", np.std(array,axis=0))
print("Per row mean:", np.mean(array,axis=1), "median:", np.median(array,axis=1), "std:", np.std(array,axis=1))


# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Q2(b) Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))

Q2(a)(i) Abs:
 [[1 2 3]
 [4 5 6]]
Q2(a)(ii) Percentiles (flat): [-3.5 -0.5  2.5]
Per column: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Per row: [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Q2(a)(iii) Mean(flat): -0.5 Median(flat): -0.5 Std(flat): 3.8622100754188224
Per column mean: [-1.5  1.5 -1.5] median: [-1.5  1.5 -1.5] std: [2.5 3.5 4.5]
Per row mean: [ 0.66666667 -1.66666667] median: [ 1. -4.] std: [2.05480467 4.78423336]
Q2(b) Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [39]:
#Q3
array = np.array([10, 52, 62, 16, 16, 54, 453])
# (a)
print("Q3(a)(i) Sorted:", np.sort(array))
print("Q3(a)(ii) Indices:", np.argsort(array))
print("Q3(a)(iii) 4 smallest:", np.partition(array, 4)[:4])
print("Q3(a)(iv) 5 largest:", np.partition(array, -5)[-5:])


# (b)
array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_mask = array2 == array2.astype(int)
print("Q3(b)(i) Integer elements:", array2[int_mask])
print("Q3(b)(ii) Float elements:", array2[~int_mask])

Q3(a)(i) Sorted: [ 10  16  16  52  54  62 453]
Q3(a)(ii) Indices: [0 3 4 1 5 2 6]
Q3(a)(iii) 4 smallest: [16 10 16 52]
Q3(a)(iv) 5 largest: [ 16  52  62  54 453]
Q3(b)(i) Integer elements: [1. 2. 3. 2.]
Q3(b)(ii) Float elements: [1.2 2.2]


In [47]:
#Q4
# (a) Function to read image and save as txt
def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("image_grey.txt", arr, fmt="%d")
        print("Saved grayscale image as image_grey.txt")
    else:
        np.savetxt("image_rgb.txt", arr.reshape(-1, arr.shape[-1]), fmt="%d")
        print("Saved RGB image as image_rgb.txt")